# This role does the following tasks.
# 1. Get the package of the runc binaries.
# 2. Place them in the right location.
# 3. Run the install command for the binaries.
# 4. Run the command to verify runc is setup correctly.
---
- name: "Check if the runc binaries are already downloaded."
  stat:
    path: /tmp/runc.amd64
  register: runc_downloaded
  become: true
  become_user: root
  tags: runc_setup

- name: "Check if runc binaries are already installed."
  stat:
    path: "{{ runc_package_dir }}"
  register: runc_installed
  become: true
  become_user: root
  tags: runc_setup

- name: "Download the runc binaries package."
  ansible.builtin.get_url:
    url: "{{ runc_package_url }}"
    dest: /tmp/runc.amd64
  become: true
  become_user: root
  when: not runc_downloaded.stat.exists and not runc_installed.stat.exists
  tags: runc_setup

- name: "Copy the runc binaries in the sbin directory."
  copy:
    src: /tmp/runc.amd64
    dest: "{{ runc_package_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  become: true
  become_user: root
  when: not runc_installed.stat.exists
  tags: runc_setup

- name: "Install runc binaries."
  command: "install -m 755 /tmp/runc.amd64 {{ runc_package_dir }}"
  become: true
  become_user: root
  when: not runc_installed.stat.exists
  tags: runc_setup

- name: "Verify runc has been installed correctly."
  command: "runc --version"
  register: runc_version
  become: true
  become_user: root
  tags: runc_setup

- name: "Verify runc has been installed correctly."
  debug:
    msg: "{{ runc_version.stdout }}"
  become: true
  become_user: root
  when: runc_version is defined
  tags: runc_setup

- name: "Remove runc binaries from the temp directory."
  file:
    path: /tmp/runc.amd64
    state: absent
  become: true
  become_user: root
  when: runc_version is defined and runc_installed.stat.exists
  tags: runc_setup